name       : perl-xml-libxslt
version    : 1.95
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-1.95.tar.gz : f1ca21135acc53af9f175958ef5fceb453fd0ef383cfb0e6ef6ea24031f3ef35
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Interface to the GNOME libxslt library
description: |
    Interface to the GNOME libxslt library
builddeps  :
    - pkgconfig(libxslt)
    - perl-xml-libxml
rundeps    :
    - perl-xml-libxml
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
