name       : perl-xml-libxslt
version    : '2.002001'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-2.002001.tar.gz : df8927c4ff1949f62580d1c1e6f00f0cd56b53d3a957ee4b171b59bffa63b2c0
homepage   : https://metacpan.org/pod/XML::LibXSLT
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : XML::LibXSLT - Interface to the GNOME libxslt library
description: |
    This module is an interface to the GNOME project's libxslt. This is an extremely good XSLT engine, highly compliant and also very fast. I have tests showing this to be more than twice as fast as Sablotron.
builddeps  :
    - pkgconfig(libxslt)
    - libgcrypt-devel
    - perl-xml-libxml
    - perl-test-pod
rundeps    :
    - perl-xml-libxml
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
