name       : perl-xml-libxslt
version    : '1.99'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-1.99.tar.gz : 127e17a877fb61e47b9e8b87bf8daad31339a62a00121f9751d522b438b0f7f0
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Interface to the GNOME libxslt library
description: |
    Interface to the GNOME libxslt library
builddeps  :
    - pkgconfig(libxslt)
    - libgcrypt-devel
    - perl-xml-libxml
    - perl-test-pod
rundeps    :
    - perl-xml-libxml
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
